##################################################################################################
# payment service and deployment
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
    service: payment
spec:
  ports:
  - port: 8084
    targetPort: 8084
    name: grpc
  selector:
    app: payment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onlineboutique-payment
  labels:
    account: payment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      serviceAccountName: onlineboutique-payment
      containers:
      - name: payment
        image: appnetorg/onlineboutique-grpc:latest
        command: ["/app/onlineboutique"]
        args: ["payment"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
        env:
        - name: LOG_LEVEL
          value: info
      - name: symphony-proxy
        image: appnetorg/symphony-proxy-h2:latest
        command:
        - /app/proxy
        securityContext:
          runAsUser: 1337
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        env:
        - name: LOG_LEVEL
          value: info
        - name: ENABLE_PACKET_BUFFERING
          value: "true"
      initContainers:
      - name: set-iptables
        image: appnetorg/symphony-proxy-h2-init-container-grpc:latest
        command:
        - /bin/sh
        - -c
        - bash /apply_symphony_iptables.sh
        securityContext:
          runAsUser: 0
          capabilities:
            add:
            - NET_ADMIN
---
# volume and persistent volume claim of `payment`
apiVersion: v1
kind: PersistentVolume
metadata:
  name: payment-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: payment-storage
  hostPath:
    path: /data/volumes/payment-pv
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: payment-storage
  resources:
    requests:
      storage: 1Gi
---
